### ISSUE TITLE
product show > product section checklist

### ISSUE THREAD

**Issue by exploit-J** [exploit-J/practice-tomorrow#1]
## checklist

- Tab + TabPanel 구조
  - [ ] `role`을 사용해서 유기적인 연결관계 구축
- 공통 컴포넌트
  - [x] Tabpanel 내 헤더 영역
    - [x] 텍스트 only
    - [x] 텍스트+뱃지+아이콘링크
    - [x] 텍스트+뱃지+텍스트 링크
    - [x] 텍스트+뱃지+아이콘버트(드랍다운/sm-only)
  - [ ] Tabpanel 내 `table`
